### PR TITLE
level fixes

### PR DESCRIPTION
**Pull request by cryptish**
```
- fix incorrect handling of INFO
- allow logging to be disabled via OFF or DISABLED
- more efficient level checking
- flag MojoX::Log::Declare compatibility gotcha
- test case-insensitivity
- fix doc typos
```

This is virtually the same as the [previous pull request](https://github.com/companieshouse/Log-Declare/pull/3), but includes a fix for the Hypnotoad issue, which was actually a [MojoX::Log::Declare compatibility](https://github.com/companieshouse/MojoX-Log-Declare/blob/d76f15344628bc830a4d4f0f75d0c84c787a9cb6/lib/MojoX/Log/Declare.pm#L16) issue (fixed by restoring `@Log::Declare::level_priority`).

### CODE REVIEW

**Comment by cryptish** [comment]
Added a patch to ensure the module behaves as documented re: short-circuiting :-) Currently, without additional hooks (which I'll restore in the next commit...), all of the exported level subs (`trace`, `debug` &c.) return true, so the arguments are always evaluated and `log` is always called. This patch makes the exported subs behave as expected by default, which leads to a significant speedup/non-slowdown for _all code_ which (non-trivially) uses `Log::Declare` (without namespace hooks) e.g., in my tests, between 1.5x - 2.5x.

**Comment by ian-kent** [comment]
Looks like a nice performance gain, but can't get tests to pass

levels.pl fails with compilation failures (seems to be related to the way levels.pl is invoked) - see https://gist.github.com/ian-kent/6b52086154b2f3ba92f5

If I change levels.t it does a bit better - see https://gist.github.com/ian-kent/5a035e7778738dc4fdc4

```
-    my $stderr = qx{ $^X -Mblib "$Bin/levels.pl" 2>&1 }; # XXX use Capture::Tiny
+    my $stderr = qx{ $^X -Mlib "$Bin/levels.pl" 2>&1 }; # XXX use Capture::Tiny
```

Doesn't feel right to invoke another script to test STDERR output - until its all cleaned up a bit, is there any reason not to use the same technique that other tests in Log::Declare use (i.e. capturing STDERR in a BEGIN block)?

**Comment by cryptish** [comment]
Re: the tests: I can only reproduce those errors by _not_ running the standard:
- `perl Makefile.PL`
- `make`

steps. After those, either of the following should work:
- `make test`
- `prove t`

Is there some reason these steps aren't being/can't be run?

> is there any reason not to use the same technique that other tests in Log::Declare use (i.e. capturing STDERR in a BEGIN block)?

Mainly because I don't understand it :-) The external script approach has the virtue of being abstractable/reusable (it looks like the `SAVEERR` incantations need to be duplicated throughout `t/log_declare.t`) and easy for my simple brain to understand. A better solution along those lines, as per the comment, would be to use [`Capture::Tiny`](http://search.cpan.org/perldoc?Capture%3A%3ATiny).

But maybe we don't need either?

### Capturing the translated code

We can see the translated code like this on the command-line:

``` perl
perl -MO=Deparse script.pl
```

There are various ways to do this in a test. The log calls can even be in the same file e.g.:

``` perl
#!/usr/bin/env perl

sub test1 {
    package test1;
    use Log::Declare;
    info 'test1!';
    warn 'warn';
}

sub test2 {
    package test2;
    use Log::Declare qw(:nowarn);
    info 'test2!';
    warn 'warn';
}

use strict;
use warnings;
use feature qw(say);

use B::Deparse;

my $deparse = B::Deparse->new();
my $body1 = $deparse->coderef2text(\&test1);
my $body2 = $deparse->coderef2text(\&test2);

say $body1;
say $body2;
```

Output:

``` perl
{
    package test1;
    'Log::Declare'->log('info', ['GENERAL'], 'test1!') if info();
    'Log::Declare'->log('warn', ['GENERAL'], 'warn') if warn();
}
{
    package test2;
    'Log::Declare'->log('info', ['GENERAL'], 'test2!') if info();
    warn 'warn';
}
```

### Capturing the logged output

For checking the logged output, we could break out the `print` statement into a separate sub. This would make it easy to (portably) test the output, log to STDOUT instead of STDERR, hook in other appenders &c. e.g.:

``` perl
sub log {
    my ($self, $level_name, $categories, $message) = @_;
    # ...
    return $self->append("$$ [$ts] [$level_name]$categories $message");
}

sub append {
    my ($self, $message) = @_;
    return CORE::print STDERR $message;
}
```

**Comment by ian-kent** [comment]
Ah I wasn't running make first, that'd be it!

> The external script approach has the virtue of being abstractable/reusable (it looks like the `SAVEERR` incantations need to be duplicated throughout `t/log_declare.t`) and easy for my simple brain to understand. A better solution along those lines, as per the comment, would be to use [`Capture::Tiny`](http://search.cpan.org/perldoc?Capture%3A%3ATiny).

We could refactor the tests to make it more reusable, but its essentially what Capture::Tiny would do for us anyway.

> But maybe we don't need either?

Using B::Deparse is a really good idea - I think we should be doing that too, but I wouldn't replace the existing tests which check the log output, they're still valid tests against what the default logger should do.

> hook in other appenders

We already can - the "simple" way is to call `Log::Declare->log_statement("")` from a `BEGIN{}` block before the `use Log::Declare` line, so log statements can be transformed into any output we want.

Log::Declare did originally have support for various logger backends, but that functionality was removed because it didn't really fit with what Log::Declare was trying to do.

**Comment by ian-kent** [comment]
and looks ok to merge :+1:

**Pull request merged**
